/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package calculadora;

import java.awt.Font;
import javax.swing.JButton;
import javax.swing.JComponent;

import javax.swing.JOptionPane;


/**
 *
 * @author beirith
 */
public class Calculadora extends javax.swing.JPanel implements java.beans.Customizer {

    private final int TAMANHO_MAXIMO = 20;
    private boolean limparNoProximoDigito;
    private double ultimoNumero;
    private String operador = "0";
    private JButton jbnButtons[];
    private String fonte = null;

    
    public Font getFonteComponentes() {
      
        return campoVisor.getFont();
    }
    
    public void setFonteTodosComponentes(String fonte, int estilo, int tamanho) {
        
        Font font = new Font(fonte, estilo, tamanho);
        for(int i = 0; i<jbnButtons.length; i++){
            jbnButtons[i].setFont(font);
        }
        campoVisor.setFont(font);
    }

    private Object bean;
    private boolean calcPanelVisible = true;
    private String value = "0";
    boolean alternar = true;
   
    
     public Calculadora() {
        initComponents();
        defineButtons();
    }

    /**
     * Get the value of value
     *
     * @return the value of value
     */
    public String getValue() {
        return value = campoVisor.getText();
    }

    /**
     * Set the value of value
     *
     * @param value new value of value
     */
    public void setValue(String value) {
        campoVisor.setText(value);
    }
  
    /**
     * Get the value of calcPanelVisible
     *
     * @return the value of calcPanelVisible
     */
    public boolean isCalcPanelVisible() {
        return calcPanelVisible;
    }

    /**
     * Set the value of calcPanelVisible
     *
     * @param calcPanelVisible new value of calcPanelVisible
     */
    public void setCalcPanelVisible(boolean calcPanelVisible) {
            setVisible(calcPanelVisible);
    }

    public void setObject(Object bean) {
        this.bean = bean;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the FormEditor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        campoVisor = new javax.swing.JTextField();
        jButton7 = new javax.swing.JButton();
        jButtonDivisao = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButtonMultiplicacao = new javax.swing.JButton();
        jButtonSubtracao = new javax.swing.JButton();
        jButtonSoma = new javax.swing.JButton();
        jButtonIgual = new javax.swing.JButton();
        jButtonLimpar = new javax.swing.JButton();
        jButtonDecimal = new javax.swing.JButton();
        jButton0 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jlbOutput = new javax.swing.JLabel();
        botaoMinimizar = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));

        campoVisor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoVisorActionPerformed(evt);
            }
        });

        jButton7.setText("7");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoClicado(evt);
            }
        });

        jButtonDivisao.setText("/");
        jButtonDivisao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoClicado(evt);
            }
        });

        jButton9.setText("9");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoClicado(evt);
            }
        });

        jButton8.setText("8");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoClicado(evt);
            }
        });

        jButton4.setText("4");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoClicado(evt);
            }
        });

        jButton5.setText("5");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoClicado(evt);
            }
        });

        jButton6.setText("6");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoClicado(evt);
            }
        });

        jButtonMultiplicacao.setText("*");
        jButtonMultiplicacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoClicado(evt);
            }
        });

        jButtonSubtracao.setText("-");
        jButtonSubtracao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoClicado(evt);
            }
        });

        jButtonSoma.setText("+");
        jButtonSoma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoClicado(evt);
            }
        });

        jButtonIgual.setText("=");
        jButtonIgual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoClicado(evt);
            }
        });

        jButtonLimpar.setText("CE");
        jButtonLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoClicado(evt);
            }
        });

        jButtonDecimal.setText(".");
        jButtonDecimal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoClicado(evt);
            }
        });

        jButton0.setText("0");
        jButton0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoClicado(evt);
            }
        });

        jButton2.setText("2");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoClicado(evt);
            }
        });

        jButton1.setText("1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoClicado(evt);
            }
        });

        jButton3.setText("3");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoClicado(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(campoVisor)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jButton4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButtonDecimal, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jButton8, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jButton5, javax.swing.GroupLayout.Alignment.TRAILING))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jButton3)
                                            .addComponent(jButton6)
                                            .addComponent(jButton9)))
                                    .addComponent(jButton0, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(jButtonLimpar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonSoma)
                            .addComponent(jButtonDivisao, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonMultiplicacao, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonSubtracao, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonIgual))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jButtonDecimal, jButtonIgual});

        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(campoVisor, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton7)
                    .addComponent(jButton8)
                    .addComponent(jButton9)
                    .addComponent(jButtonDivisao))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4)
                    .addComponent(jButton5)
                    .addComponent(jButton6)
                    .addComponent(jButtonMultiplicacao))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton3)
                    .addComponent(jButtonSubtracao))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton0)
                        .addComponent(jButtonDecimal))
                    .addComponent(jButtonSoma))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonIgual)
                    .addComponent(jButtonLimpar))
                .addGap(3, 3, 3))
        );

        botaoMinimizar.setText("--");
        botaoMinimizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minimizarTela(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(botaoMinimizar)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(111, 111, 111)
                    .addComponent(jlbOutput)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addComponent(botaoMinimizar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(87, 87, 87)
                    .addComponent(jlbOutput)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void defineButtons() {
        jbnButtons = new JButton[18];

        jbnButtons[0] = jButton0;
        jbnButtons[1] = jButton1;
        jbnButtons[2] = jButton2;
        jbnButtons[3] = jButton3;
        jbnButtons[4] = jButton4;
        jbnButtons[5] = jButton5;
        jbnButtons[6] = jButton6;
        jbnButtons[7] = jButton7;
        jbnButtons[8] = jButton8;
        jbnButtons[9] = jButton9;
        jbnButtons[10] = jButtonDecimal;
        jbnButtons[11] = jButtonIgual;
        jbnButtons[12] = jButtonDivisao;
        jbnButtons[13] = jButtonMultiplicacao;
        jbnButtons[14] = jButtonSubtracao;
        jbnButtons[15] = jButtonSoma;
        jbnButtons[16] = jButtonLimpar;
        
        
    }

    public void setValorAtual(String s) {
        campoVisor.setText(s);
    }

    public String getValorAtual() {
        return campoVisor.getText();
    }

    public void adicionarDigito(int digit) {
        if (limparNoProximoDigito) {
            setValorAtual("");
        }

        String campoTexto = getValorAtual();

        if (campoTexto.indexOf("0") == 0) {
            campoTexto = campoTexto.substring(1);
        }

        if ((!campoTexto.equals("0") || digit > 0) && campoTexto.length() < TAMANHO_MAXIMO) {
            setValorAtual(campoTexto + digit);
        }


        limparNoProximoDigito = false;
    }

    public void adicionarPontoDecimal() {
       
        if (limparNoProximoDigito) {
            setValorAtual("");
        }

        String campoTexto = getValorAtual();


        // Se o campo de texto ja conter ponto decimal, nao faça nada
        if (campoTexto.indexOf(".") < 0) {
            setValorAtual(new String(campoTexto + "."));
        }
    }

    public void clearAll() {
        setValorAtual("0");
        operador = "0";
        ultimoNumero = 0;
        limparNoProximoDigito = true;
    }

    public double pegarNumeroVisor() {
        String input = campoVisor.getText();
        
        try{
         return Double.parseDouble(input);
        }catch(NumberFormatException e){
            campoVisor.setText("0");
        JOptionPane.showMessageDialog(null, "Exeção: Apenas números!");    
        }
        return 0;
        
    
                
    }

    public void processarOperador(String op) {
    
            double numeroVisor = pegarNumeroVisor();

            if (!operador.equals("0")) {
                double result = realizarOperacao();
                mostrarResultado(result);
                ultimoNumero = result;

            } else {
                ultimoNumero = numeroVisor;
            }

            limparNoProximoDigito = true;
            operador = op;
        
    }

    public double realizarOperacao() {
        double result = 0;
        double numeroVisor = pegarNumeroVisor();

        if (operador.equals("/")) {
            if (numeroVisor == 0) {
                JOptionPane.showMessageDialog(null, "Exeção: Divisão por zero!");
            }

            result = ultimoNumero / numeroVisor;
        }

        if (operador.equals("*")) {
            result = ultimoNumero * numeroVisor;
        }

        if (operador.equals("-")) {
            result = ultimoNumero - numeroVisor;
        }

        if (operador.equals("+")) {
            result = ultimoNumero + numeroVisor;
        }

        return result;
    }

    void processarIgual() {
            double resultado = 0;
            resultado = realizarOperacao();
            mostrarResultado(resultado);
            operador = "0";
        
    }

    public void mostrarResultado(double result) {
        setValorAtual(Double.toString(result));
        ultimoNumero = result;
        limparNoProximoDigito = true;
    }

    private void botaoClicado(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoClicado

        for (int i = 0; i < jbnButtons.length; i++) {
            if (evt.getSource() == jbnButtons[i]) {
                switch (i) {
                    case 0:
                        adicionarDigito(i);
                        break;

                    case 1:
                        adicionarDigito(i);
                        break;

                    case 2:
                        adicionarDigito(i);
                        break;

                    case 3:
                        adicionarDigito(i);
                        break;

                    case 4:
                        adicionarDigito(i);
                        break;

                    case 5:
                        adicionarDigito(i);
                        break;

                    case 6:
                        adicionarDigito(i);
                        break;

                    case 7:
                        adicionarDigito(i);
                        break;

                    case 8:
                        adicionarDigito(i);
                        break;

                    case 9:
                        adicionarDigito(i);
                        break;


                    case 10:	// decimal
                        adicionarPontoDecimal();
                        break;

                    case 11:	// igual
                        processarIgual();
                        break;

                    case 12:	// divisao
                        processarOperador("/");
                        break;

                    case 13:	// multiplicacao
                        processarOperador("*");
                        break;

                    case 14:	// subtracao
                        processarOperador("-");
                        break;

                    case 15:	// soma
                        processarOperador("+");
                        break;

                    case 16:	// Limpar
                        clearAll();
                        break;
                }
            }
        }
    }//GEN-LAST:event_botaoClicado

    private void campoVisorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoVisorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoVisorActionPerformed

    private void minimizarTela(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minimizarTela
     
       alternar = !alternar;
       jPanel2.setVisible(alternar);
        
    }//GEN-LAST:event_minimizarTela

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoMinimizar;
    private javax.swing.JTextField campoVisor;
    private javax.swing.JButton jButton0;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JButton jButtonDecimal;
    private javax.swing.JButton jButtonDivisao;
    private javax.swing.JButton jButtonIgual;
    private javax.swing.JButton jButtonLimpar;
    private javax.swing.JButton jButtonMultiplicacao;
    private javax.swing.JButton jButtonSoma;
    private javax.swing.JButton jButtonSubtracao;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel jlbOutput;
    // End of variables declaration//GEN-END:variables
}
